// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2L9e65OlMaSLWkS03FTUNEbtU-rvZYQ',
    appId: '1:1088641555757:web:0b793c93300892469c07a4',
    messagingSenderId: '1088641555757',
    projectId: 'musik-2cd99',
    authDomain: 'musik-2cd99.firebaseapp.com',
    storageBucket: 'musik-2cd99.firebasestorage.app',
    measurementId: 'G-HF6RX03SW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzfhbtcjhOayYf3P7LlBncAgBhJbBjcpE',
    appId: '1:1088641555757:android:6157de59c599102f9c07a4',
    messagingSenderId: '1088641555757',
    projectId: 'musik-2cd99',
    storageBucket: 'musik-2cd99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMx2gD0qCMejdvFzFcJdCAamzC6lYzh18',
    appId: '1:1088641555757:ios:ebc5c98efec149c09c07a4',
    messagingSenderId: '1088641555757',
    projectId: 'musik-2cd99',
    storageBucket: 'musik-2cd99.firebasestorage.app',
    iosBundleId: 'com.example.musikapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMx2gD0qCMejdvFzFcJdCAamzC6lYzh18',
    appId: '1:1088641555757:ios:ebc5c98efec149c09c07a4',
    messagingSenderId: '1088641555757',
    projectId: 'musik-2cd99',
    storageBucket: 'musik-2cd99.firebasestorage.app',
    iosBundleId: 'com.example.musikapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf2L9e65OlMaSLWkS03FTUNEbtU-rvZYQ',
    appId: '1:1088641555757:web:98e3fb561a3c17209c07a4',
    messagingSenderId: '1088641555757',
    projectId: 'musik-2cd99',
    authDomain: 'musik-2cd99.firebaseapp.com',
    storageBucket: 'musik-2cd99.firebasestorage.app',
    measurementId: 'G-8TRRYGXJWL',
  );
}
